title: wiki.chip.guide
baseurl: /
url: "https://wiki.chip.guide"
plugins:
  - jekyll-feed

# Permalinks
permalink: /page/:title/

github:
  repo:           https://github.com/chipguide/wiki

author:
  name:           'chip.guide'
  url:            https://chip.guide